version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    entrypoint: wait-for postgres:5432 -t 40 -- sh -c "npm install && npm run migrate:dev && npm run start:dev"
    restart: always
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres:
    name: travel-db
