version: '3.9'

services:
  database:
    image: postgres:13
    restart: always
    container_name: travel-control-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_USER
      POSTGRES_DB: POSTGRES_USER
    volumes:
      - pgdata:/data/postgres

  api:
    build: .
    container_name: travel-control-api
    restart: always
    ports:
      - 5050:5050
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
